package remeberme.domain;

public class UserProfile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_PROFILE.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_PROFILE.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_PROFILE.id
     *
     * @return the value of USER_PROFILE.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_PROFILE.id
     *
     * @param id the value for USER_PROFILE.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_PROFILE.type
     *
     * @return the value of USER_PROFILE.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_PROFILE.type
     *
     * @param type the value for USER_PROFILE.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }
}