package edu.ldcollege.mapping;

import edu.ldcollege.domain.LdHomeWork;
import edu.ldcollege.domain.LdHomeWorkExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface LdHomeWorkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_homework
     *
     * @mbg.generated
     */
    @SelectProvider(type=LdHomeWorkSqlProvider.class, method="countByExample")
    long countByExample(LdHomeWorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_homework
     *
     * @mbg.generated
     */
    @DeleteProvider(type=LdHomeWorkSqlProvider.class, method="deleteByExample")
    int deleteByExample(LdHomeWorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_homework
     *
     * @mbg.generated
     */
    @Delete({
        "delete from ld_homework",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_homework
     *
     * @mbg.generated
     */
    @Insert({
        "insert into ld_homework (id, userId, ",
        "classId, lessionId, ",
        "homeworkFilePath, homeworkFileName, ",
        "starCount, negativeCount, ",
        "correctFlag, BestFlag, ",
        "createDate)",
        "values (#{id,jdbcType=INTEGER}, #{userid,jdbcType=INTEGER}, ",
        "#{classid,jdbcType=INTEGER}, #{lessionid,jdbcType=INTEGER}, ",
        "#{homeworkfilepath,jdbcType=VARCHAR}, #{homeworkfilename,jdbcType=VARCHAR}, ",
        "#{starcount,jdbcType=INTEGER}, #{negativecount,jdbcType=INTEGER}, ",
        "#{correctflag,jdbcType=INTEGER}, #{bestflag,jdbcType=BIT}, ",
        "#{createdate,jdbcType=DATE})"
    })
    int insert(LdHomeWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_homework
     *
     * @mbg.generated
     */
    @InsertProvider(type=LdHomeWorkSqlProvider.class, method="insertSelective")
    int insertSelective(LdHomeWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_homework
     *
     * @mbg.generated
     */
    @SelectProvider(type=LdHomeWorkSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="userId", property="userid", jdbcType=JdbcType.INTEGER),
        @Result(column="classId", property="classid", jdbcType=JdbcType.INTEGER),
        @Result(column="lessionId", property="lessionid", jdbcType=JdbcType.INTEGER),
        @Result(column="homeworkFilePath", property="homeworkfilepath", jdbcType=JdbcType.VARCHAR),
        @Result(column="homeworkFileName", property="homeworkfilename", jdbcType=JdbcType.VARCHAR),
        @Result(column="starCount", property="starcount", jdbcType=JdbcType.INTEGER),
        @Result(column="negativeCount", property="negativecount", jdbcType=JdbcType.INTEGER),
        @Result(column="correctFlag", property="correctflag", jdbcType=JdbcType.INTEGER),
        @Result(column="BestFlag", property="bestflag", jdbcType=JdbcType.BIT),
        @Result(column="createDate", property="createdate", jdbcType=JdbcType.DATE)
    })
    List<LdHomeWork> selectByExample(LdHomeWorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_homework
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, userId, classId, lessionId, homeworkFilePath, homeworkFileName, starCount, ",
        "negativeCount, correctFlag, BestFlag, createDate",
        "from ld_homework",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="userId", property="userid", jdbcType=JdbcType.INTEGER),
        @Result(column="classId", property="classid", jdbcType=JdbcType.INTEGER),
        @Result(column="lessionId", property="lessionid", jdbcType=JdbcType.INTEGER),
        @Result(column="homeworkFilePath", property="homeworkfilepath", jdbcType=JdbcType.VARCHAR),
        @Result(column="homeworkFileName", property="homeworkfilename", jdbcType=JdbcType.VARCHAR),
        @Result(column="starCount", property="starcount", jdbcType=JdbcType.INTEGER),
        @Result(column="negativeCount", property="negativecount", jdbcType=JdbcType.INTEGER),
        @Result(column="correctFlag", property="correctflag", jdbcType=JdbcType.INTEGER),
        @Result(column="BestFlag", property="bestflag", jdbcType=JdbcType.BIT),
        @Result(column="createDate", property="createdate", jdbcType=JdbcType.DATE)
    })
    LdHomeWork selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_homework
     *
     * @mbg.generated
     */
    @UpdateProvider(type=LdHomeWorkSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") LdHomeWork record, @Param("example") LdHomeWorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_homework
     *
     * @mbg.generated
     */
    @UpdateProvider(type=LdHomeWorkSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") LdHomeWork record, @Param("example") LdHomeWorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_homework
     *
     * @mbg.generated
     */
    @UpdateProvider(type=LdHomeWorkSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(LdHomeWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_homework
     *
     * @mbg.generated
     */
    @Update({
        "update ld_homework",
        "set userId = #{userid,jdbcType=INTEGER},",
          "classId = #{classid,jdbcType=INTEGER},",
          "lessionId = #{lessionid,jdbcType=INTEGER},",
          "homeworkFilePath = #{homeworkfilepath,jdbcType=VARCHAR},",
          "homeworkFileName = #{homeworkfilename,jdbcType=VARCHAR},",
          "starCount = #{starcount,jdbcType=INTEGER},",
          "negativeCount = #{negativecount,jdbcType=INTEGER},",
          "correctFlag = #{correctflag,jdbcType=INTEGER},",
          "BestFlag = #{bestflag,jdbcType=BIT},",
          "createDate = #{createdate,jdbcType=DATE}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(LdHomeWork record);
}