package edu.ldcollege.mapping;

import edu.ldcollege.domain.LdHomeWorkFB;
import edu.ldcollege.domain.LdHomeWorkFBExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface LdHomeWorkFBMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_homeworkfb
     *
     * @mbg.generated
     */
    @SelectProvider(type=LdHomeWorkFBSqlProvider.class, method="countByExample")
    long countByExample(LdHomeWorkFBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_homeworkfb
     *
     * @mbg.generated
     */
    @DeleteProvider(type=LdHomeWorkFBSqlProvider.class, method="deleteByExample")
    int deleteByExample(LdHomeWorkFBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_homeworkfb
     *
     * @mbg.generated
     */
    @Delete({
        "delete from ld_homeworkfb",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_homeworkfb
     *
     * @mbg.generated
     */
    @Insert({
        "insert into ld_homeworkfb (id, myid, ",
        "userId, homeworkId, ",
        "levelFlag, mark)",
        "values (#{id,jdbcType=INTEGER}, #{myid,jdbcType=INTEGER}, ",
        "#{userid,jdbcType=INTEGER}, #{homeworkid,jdbcType=INTEGER}, ",
        "#{levelflag,jdbcType=CHAR}, #{mark,jdbcType=VARCHAR})"
    })
    int insert(LdHomeWorkFB record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_homeworkfb
     *
     * @mbg.generated
     */
    @InsertProvider(type=LdHomeWorkFBSqlProvider.class, method="insertSelective")
    int insertSelective(LdHomeWorkFB record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_homeworkfb
     *
     * @mbg.generated
     */
    @SelectProvider(type=LdHomeWorkFBSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="myid", property="myid", jdbcType=JdbcType.INTEGER),
        @Result(column="userId", property="userid", jdbcType=JdbcType.INTEGER),
        @Result(column="homeworkId", property="homeworkid", jdbcType=JdbcType.INTEGER),
        @Result(column="levelFlag", property="levelflag", jdbcType=JdbcType.CHAR),
        @Result(column="mark", property="mark", jdbcType=JdbcType.VARCHAR)
    })
    List<LdHomeWorkFB> selectByExample(LdHomeWorkFBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_homeworkfb
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, myid, userId, homeworkId, levelFlag, mark",
        "from ld_homeworkfb",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="myid", property="myid", jdbcType=JdbcType.INTEGER),
        @Result(column="userId", property="userid", jdbcType=JdbcType.INTEGER),
        @Result(column="homeworkId", property="homeworkid", jdbcType=JdbcType.INTEGER),
        @Result(column="levelFlag", property="levelflag", jdbcType=JdbcType.CHAR),
        @Result(column="mark", property="mark", jdbcType=JdbcType.VARCHAR)
    })
    LdHomeWorkFB selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_homeworkfb
     *
     * @mbg.generated
     */
    @UpdateProvider(type=LdHomeWorkFBSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") LdHomeWorkFB record, @Param("example") LdHomeWorkFBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_homeworkfb
     *
     * @mbg.generated
     */
    @UpdateProvider(type=LdHomeWorkFBSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") LdHomeWorkFB record, @Param("example") LdHomeWorkFBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_homeworkfb
     *
     * @mbg.generated
     */
    @UpdateProvider(type=LdHomeWorkFBSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(LdHomeWorkFB record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_homeworkfb
     *
     * @mbg.generated
     */
    @Update({
        "update ld_homeworkfb",
        "set myid = #{myid,jdbcType=INTEGER},",
          "userId = #{userid,jdbcType=INTEGER},",
          "homeworkId = #{homeworkid,jdbcType=INTEGER},",
          "levelFlag = #{levelflag,jdbcType=CHAR},",
          "mark = #{mark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(LdHomeWorkFB record);
}